name: BabyBrujin

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  create_pull_request:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get branch name
        id: branch-name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          source_branch: ${{ steps.branch-name.outputs.BRANCH_NAME }}
          destination_branch: "main"
          pr_title: "Pull Request from ${{ steps.branch-name.outputs.BRANCH_NAME }}"
          pr_draft: false

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
          working-directory: ./baby_brujin

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
          working-directory: ./baby_brujin